pollster/pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
	# Empty quotes (want it to be /polls)
	# it will be polls/'(whatever)'
	# leave it blank, should be index.  
	path('', views.index, name='index'),
]

pollster/polls/urls.py
# To deal with urls.
# https://docs.djangoproject.com/en/2.2/ref/urls/

# path(route, view, kwargs=None, name=None)
# route: String that contains url pattern
# 	may contain <> to send it as an argument to the view.
#	can also include converter, eg. <int:question_id>
# view: View function
# kwargs: Allows to pass additional arguments.
# name: Naming arguments

from django.urls import path

# from all import views
from . import views

# create namespace 
app_name = 'polls'
urlpatterns = [
	# Empty quotes (want it to be /polls)
	# it will be polls/'(whatever)'
	# leave it blank, should be index. 
	path('', views.index, name='index'),

	# Details, results, vote functions in views.py gets <int:question_id> 
	# passed to it from here.
	path('<int:question_id>', views.detail, name='detail'),
	path('<int:question_id>/results/', views.results, name='results'),
	path('<int:question_id>/vote/', views.vote, name='vote'),

]

pollster/pollster/urls.py
from django.contrib import admin
# include; if we are going to bring in another urls file.  
from django.urls import include, path

urlpatterns = [
    # For landing, from pages app,
    path('', include('pages.urls')),

	# for anything polls/; include polls.urls.
	# As soon as we go to /polls/ anything, it'll look at the polls.urls file. 
	path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

pollster/pages/models.py
from django.db import models

# Create your models here.

pollster/polls/models.py
from django.db import models

class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')

	def __str__(self):
		return self.question_text

class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE) 
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text 

pollster/pages/views.py
from django.shortcuts import render

def index(request):
	return render(request, 'pages/index.html')

pollster/polls/views.py
# A view function, or view for short, is a Python function 
# that takes a Web request and returns a Web response. 

# This response can be the HTML contents of a Web page, 
# or a redirect, or a 404 error, or an XML document, 
# or an image . . . or anything, really. 

# The view itself contains whatever arbitrary logic is 
# necessary to return that response. 

# render(request, template_name, context=None, content_type=None, status=None, using=None)¶
# Combines a given template with a given context dictionary 
# and returns an HttpResponse object with that rendered text.



from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .models import Question,Choice


# Get questions and display them.
def index(request):
	# Pass through data to the polls template polls/index.html.
	# List questions: up to 5, order decending (latest). 
	latest_question_list = Question.objects.order_by('-pub_date')[:5]

	context = {'latest_question_list': latest_question_list}

	# pass in request, and location of template.
	return render(request, "polls/index.html", context)

# show specific question and choices
def detail(request, question_id):
	try:
		# Getting data from DB.
		# Using pk question_id, as parameter, 
		# which is going to come from the url.
		question = Question.objects.get(pk=question_id)
	except Question.DoesNotExist:
		raise Http404("Question does not exist.")
	return render(request, 'polls/detail.html', { 'question': question })

# get question and display results
def results(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	return render(request, 'polls/results.html', { 'question':question })


# Vote for a question choice
def vote(request, question_id):
	# print the choice value id 
	print(request.POST['choice'])

	# get the question, based on the choice id.
	question = get_object_or_404(Question, pk=question_id)
	
	try: 
		# set var selected_choice based on that choice
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		# Redisplay the question voting form...
		# If they don't select a choice, 
		# render the details template and display error msg.
		return render(request, 'polls/detail.html', {
			'question': question,
			'error_message': "You didn't select a choice.",
			}) 
	else:
		# add 1 to the selected_choice votes!
		selected_choice.votes += 1
		selected_choice.save()

		# Always return an HttpResponseRedirect after
		# successfully dealing with POST data.
		# This prevents data from being posted twice if 
		# a user hits the Back button.
		return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))

pollster/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width", inital-scale=1.0>
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<!-- Bootstrap href -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

	<title>Pollster {% block title %}{% endblock %}</title>
</head>

<body>
	<!-- NavBar -->
	<!-- refering to _navbar.html partials template 
		w/ bootstrap navbar template -->
	{% include 'partials/_navbar.html' %}

	<div class="container">
		<div class="row">
			<div class="col-md-6 m-auto">
				<!-- Output any content/templates
				 to display here -->
				{% block content %}{% endblock %}
			</div>
		</div>
	</div>

</body>
</html>

pollster/templates/pages/index.html
<!-- landing page! for pages app -->
{% extends 'base.html' %}
{% block content %}

<div class="card text-center">
	<div class = "card-body">
		<h1>Welcome To Pollster</h1>
		<p>Web frameworks... Django, Flask, or Web2py? Vue, React, Angular? etc.</p>
		<a class="btn btn-dark" href="{% url 'polls:index' %}">View Available Polls</a>
	</div>	
</div>
{% endblock %}

pollster/templates/partials/_navbar.html
<!-- -->
<!-- the underscore in _navbar.html 
signifies that this is a partial and not a full template -->

<!-- A bootstrap navbar! -->
<!-- Going to be used in base.html -->

<nav class="navbar navbar-dark bg-priamry mb-4">
	<div class="container">
		<a class="navbar-brand" href="/">Pollster</a>
	</div>
	
</nav>

pollster/templates/polls/detail.html
<!-- Details html template -->

{% extends 'base.html' %}
{% block content %}

<!--  -->
<!-- btn going back to polls (polls index) -->
<a class="btn btn-secondary btn-sm mb-3" href="{% url 'polls:index' %}"> Back to Polls </a>
<!-- The question: -->
<h1 class="text-center mb-3">{{ question.question_text }}</h1>

<!-- if error message, display in this alert -->
{% if error_message %}
<p class="alert alert-danger">
	<strong>{{ error_message }}</strong>
</p>
{% endif %}

<!-- Form w/ action that goes to polls/vote view -->
<form action="{% url 'polls:vote' question.id %}" method="post">
	<!-- csrf_token: Django security feature.
	 protects form from being submitted from somewhere else. -->
	{% csrf_token %}
	{% for choice in question.choice_set.all %}
		<!-- for each choice have a checkbox. -->
		<!-- each choice value will have id. -->
		<!-- the html id will be forloop.counter -->
		<div class="form-check">
			<input 
			type="radio" 
			name="choice"
			class="form-check-input"
			id="choice{{ forloop.counter }}"
			value="{{ choice.id }}" 
			>
			<!-- choice label will be count fromm forloop.counter -->
			<label for="choice{{ forloop.counter }}">
				{{ choice.choice_text }}
			</label>
		</div>
	{% endfor %}
	<input type="submit" value="Vote" name="btn btn-success btn-lg btn-block mt-4">
</form>

{% endblock %}

pollster/templates/polls/index.html
{% extends 'base.html' %}

{% block content %}
	<h1 class="text-center mb-3">Poll Questions</h1>

	<!-- displaying polls data -->
	{% if latest_question_list %}
		{% for question in latest_question_list %}
			<!-- using card class -->
			<div class="card mb-3">
				<div class="card-body">
					<!-- double {} for outputting data -->
					<p class="lead">{{ question.question_text }}</p>
					<!-- Refer to urls.py namespace -->
					<!-- load views (detail, results) from polls -->
					<!-- detail, priamry -->
					<a href="{% url 'polls:detail' question.id %}" class="btn btn-primary btn-sm">
						Vote now
					</a>
					<!-- results, secondary -->
					<a href="{% url 'polls:results' question.id %}" class="btn btn-secondary btn-sm">
						Results
					</a>


				</div> 
			</div>
		{% endfor %}

	{% else %}
		<p>No polls available</p>
	{% endif %}

{% endblock %}

pollster/templates/polls/results.html
<!-- Results html template -->

<!--  -->

{% extends 'base.html' %}
{% block content %}

<!-- the question text -->
<h1 class="mb-5 text-center">{{ question.question_text }}</h1>
<ul class="list-group mb-5">
	<!-- for each choice: -->
	{% for choice in question.choice_set.all %}
		<!-- text of choice: choice.choice_text -->
		<!-- number of votes: choice.votes -->
		<!-- pluralize helper. If more than 1 vote, pluralize it -->
		<li class="list-group-item">
			{{ choice.choice_text }} <span class="badge badge-success float-right">
				{{ choice.votes }} vote{{ choice.votes | pluralize }}
			</span>
		</li>
		{% endfor %}
</ul>

<!-- Btns: Back to Polls, or Vote Again -->
<a class="btn btn-secondary" href="{% url 'polls:index' %}">Back To Polls</a>
<a class="btn btn-dark" href="{% url 'polls:detail' question.id %}">Vote Again</a>

{% endblock %}